on:
  push:
    branches: [develop, master]
    paths-ignore:
      - "**/README.md"

name: Test, Build and Release apk/aab

jobs:
  build:
    name: Build apk & ipa
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"
          cache: "gradle"

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.7.5"
          channel: "stable"
          cache: true

      - name: Check Flutter version
        run: flutter --version

      - name: Get dependencies
        run: flutter pub get

      - name: Check code format
        run: dart format --set-exit-if-changed .

      - name: Analyze code
        run: flutter analyze

      - name: Run tests
        run: flutter test

      - name: Build APK
        run: flutter build apk

      - name: Build AAB (for Google Play)
        run: flutter build appbundle

      - uses: actions/upload-artifact@v3
        with:
          path: "build/app/outputs/apk/release/*.apk"

      - uses: actions/upload-artifact@v3
        with:
          path: "build/app/outputs/bundle/release/*.aab"

      - name: Build iOS (No Codesign)
        run: flutter build ios --no-codesign

      - uses: actions/upload-artifact@v3
        with:
          path: "build/ios/iphoneos/*.app"