name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java (si besoin pour tes tests)
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17' # Mets la version que ton projet utilise

      - name: Set up Flutter (si ton projet est en Dart/Flutter)
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x' # Mets la version de Flutter que tu utilises

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests with coverage
        run: flutter test --coverage

      - name: Save coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/lcov.info

      - name: SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner \
            -Dsonar.organization=goby33 \
            -Dsonar.projectKey=goby33_quizGameApp \
            -Dsonar.sources=. \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.language=dart \
            -Dsonar.sourceEncoding=UTF-8 \
            -Dsonar.tests=test \
            -Dsonar.test.inclusions="test/**" \
            -Dsonar.dart.test.reportPaths=coverage/lcov.info