name: Analyze code

on:
  push:
    branches-ignore:
      - master
  pull_request:
    branches:
      - develop
      - master

jobs:
  analyze-code:
    name: Analyze code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Run Flutter build_runner
        run: dart run build_runner build --delete-conflicting-outputs


      - name: Run Dart format check
        run: dart format --set-exit-if-changed .

      - name: Run tests (if needed)
        run: dart test